FROM michaelcontento/php:7.1

RUN apk add --no-cache \
    php7-ctype \
    php7-dom \
    php7-iconv \
    php7-pdo \
    php7-session \
    php7-tokenizer \
    php7-xml \
    php7-xmlwriter

ADD etc/ /etc
