FROM michaelcontento/php:7.2

RUN apk add --no-cache \
    'php7-ctype@php~7.2' \
    'php7-dom@php~7.2' \
    'php7-iconv@php~7.2' \
    'php7-pdo@php~7.2' \
    'php7-session@php~7.2' \
    'php7-xml@php~7.2'

ADD etc/ /etc
