FROM michaelcontento/php:7.2

RUN apk add --no-cache \
    php7-ctype@php \
    php7-dom@php \
    php7-iconv@php \
    php7-pdo@php \
    php7-session@php \
    php7-tokenizer@php \
    php7-xml@php \
    php7-xmlwriter@php

ADD etc/ /etc
