FROM michaelcontento/php:7.0

RUN apk add --no-cache \
    'php7-ctype<7.1' \
    'php7-dom<7.1' \
    'php7-iconv<7.1' \
    'php7-pdo<7.1' \
    'php7-session<7.1' \
    'php7-xml<7.1'

ADD etc/ /etc
